name: testcase
on: push

jobs:
  run-testcase:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: latest-stable
      - name: Run the testcase
        run: bash run_test.sh
